# Approach of Python

using Numpy

In [235]:
import numpy as np

## The NumPy Array Object

### Basic attributes of the ndarray class
* `shape`  
    &nbsp A tuple that contains the number of elements (i.e., the length) for each dimension (axis) of the array.  
* `size`  
    &nbsp The total number of elements in the array.
* `ndim`  
    &nbsp Number of dimensions (axes).
* `nbytes`  
    &nbsp Number of bytes used to store the data.
* `dtype`  
    &nbsp The data type of the elements in the array.
* `<Object name>[n]`  
    &nbsp The nth character of this array, the first order is 0.
* `<Object name>[n:m]`  
    &nbsp The array including characters from the order n to the order m-1, if n ≥ m-1, generate a empty array.
* `len(<Object name>)`  
    &nbsp The lenght of array.
* `type(<Object name>)`  
    &nbsp The type of array.

### The data type of the elements in the array
* Integer  
    &nbsp `np.int`, `np.int8`, `np.int16`, `np.int32`, `np.int64`(default).
* Float  
    &nbsp `np.float`, `np.float16`, `np.float32`, `np.float64`(default), `np.float128`.
* Complex  
    &nbsp `np.Complex`, `np.Complex64`, `np.Complex128`(default), `np.Complex256`. 

### Summary of NumPy functions for generating arrays
* `np.array`:  
    &nbsp Creates an array for which the elements are given by an array-like object, which, for example, can be a (nested) Python list, a tuple, an iterable sequence, or another ndarray instance.
* `np.zero`:
    &nbsp Creates an array – with the specified dimensions and data type – that is filled with zeros.
* `np.ones`:
    &nbsp Creates an array – with the specified dimensions and data type – that is filled with ones.
* `np.diag`:  
    &nbsp Creates an array with evenly spaced values between specified start, end, and, increment values.
* `np.linspace`:  
    &nbsp Creates an array with evenly spaced values between specified start and end values, using a specified number of elements.
* `np.logspace`:  
    &nbsp Creates an array with values that are logarithmically spaced between the given start and end values.
* `np.meshgrid`:  
    &nbsp Generate coordinate matrices (and higher-dimensional coordinate arrays) from onedimensional coordinate vectors.
* `np.fromfunction`:  
    &nbsp Create an array and fill it with values specified by a given function, which is evaluated for each combination of indices for the given array size.
* `np.fromfile:`  
    &nbsp Create an array with the data from a binary (or text) file. NumPy also provides a corresponding function np.tofile with which NumPy arrays can be stored to disk, and later read back using np.fromfile.
* `np.loadtxt`, `np.genfromtxt`:  
    &nbsp Creates an array from data read from a text file. For example, a comma-separated value. (CSV) file.
    The function np.genfromtxt also supports data files with missing values.
* `np.random.rand`:  
    &nbsp Generates an array with random numbers that are uniformly distributed between 0 and 1. Other types of distributions are also available in the np.random module.

### Summary of NumPy Functions for Matrix Operations
* `np.dot`:  
    &nbsp Matrix multiplication (dot product) between two given arrays representing vectors, arrays, or tensors.
* `np.inner`:  
    &nbsp Scalar multiplication (inner product) between two arrays representing vectors.
* `np.cross`:  
    &nbsp The cross product between two arrays that represent vectors.
* `np.tensordot`:  
    &nbsp Dot product along specified axes of multidimensional arrays.
* `np.outer`:  
    &nbsp Outer product (tensor product of vectors) between two arrays representing vectors.
* `np.kron`:  
    &nbsp Kronecker product (tensor product of matrices) between arrays representing matrices and higher-dimensional arrays.
* `np.einsum`:  
    &nbsp Evaluates Einstein's summation convention for multidimensional arrays.  
    &nbsp $einsum(x,y) = x[1]*y[1] + x[2]*y[2] + x[3]*y[3] + ...$

In [236]:
## 1D Array Functions

# Generation
A_source = np.array([1,6,4,3,6,2,1,9,5])
A_float = np.float128(A)
A_type = np.array([1,6,4,3,6,2,1,9,5], dtype=np.float32)

np.arange(0,10,2)                       # array([0  2  4  6  8 ])
np.arange(0,10,2, dtype=np.float32)     # array([0. 2. 4. 6. 8.])
np.linspace(0,10,2)                     # array([0. 10.])
np.empty(10)                            # array([0. 1. 2. 3. 4. 5. 6. 7. 8. 9.])
np.zeros(10)                            # array([0. 0. 0. 0. 0. 0. 0. 0. 0. 0.])
np.ones(10)                             # array([1. 1. 1. 1. 1. 1. 1. 1. 1. 1.])
np.random.random(4)                     # array([0.11097086 0.5790162  0.53776519 0.34051093])

# Operation
A = np.array([1, 2, 3, 4])
B = np.array([0, 2, 4, 6])
A + 1                                   # array([2, 3, 4, 5])
A + 1.23                                # array([2.23, 3.23, 4.23, 5.23])
A * 2                                   # array([2, 4, 6, 8])
A **2                                   # array([1, 4, 9,16])
A / 2                                   # array([0.5, 1.0, 1.5, 2.0])
A //2                                   # array([0, 1, 1, 2])
A % 2                                   # array([1, 0, 1, 0])
A + B                                   # array([1, 4, 7,10])
A - B                                   # array([1, 0,-1,-2])
A * B                                   # array([0, 4,12,24])
A / B                                   # array([inf, 1.0, 0.75, 0.66666667])
A //B                                   # array([0, 1, 0, 0])
A % B                                   # array([0, 0, 3, 4])

# Operation function
np.sum(A)                               # 10
np.sqrt(A)                              # array([1.0, 1.41421356, 1.73205081, 2.0])

# Linear algebra
A = np.matrix(A)
B = np.matrix(B)
np.dot(A, B.T)                          # matrix([[40]])
np.dot(A.T, B)                          # matrix([[ 0, 2, 4, 6],[ 0, 4, 8,12],[ 0, 6,12,18],[ 0, 8,16,24]])

U = np.matrix([1,2,3])
V = np.matrix([0,2,4])
np.cross(U, V)                          # array([[2,-4, 2]])

C = np.matrix([3,1,4,1,5,9], dtype=complex)
type(C)                                 # numpy.matrix
np.conj(C)                              # matrix([[3.-0.j, 1.-0.j, 4.-0.j, 1.-0.j, 5.-0.j, 9.-0.j]])
C.T                                     # matrix([[3.+0.j],[1.+0.j],[4.+0.j],[1.+0.j],[5.+0.j],[9.+0.j]])
C.H                                     # matrix([[3.-0.j],[1.-0.j],[4.-0.j], [1.-0.j], [5.-0.j],[9.-0.j]])
C.I                                     # The inverse matrix

# Flatten
A = np.array([[3.14, 2.71],
              [6.28, 1.41]])
A[1, 0]                                 # 6.28
A[1][0]                                 # 6.28
for row in A:                           # [3.14 2.71]
    row                                 # [6.28 1.41]
A.flatten()                             # array([3.14, 2.71, 6.28, 1.41])
A.flatten()[np.array([0,2])]            # array([3.14, 6.28])

array([3.14, 6.28])

In [269]:
## 2D Array functions

# Generation
A = np.array([[0.0, 0.1, 0.2, 0.3, 0.4],
              [1.8, 1.6, 1.4, 1.2, 1.0],
              [2.1, 2.3, 2.5, 2.7, 2.9]])
A.dtype                                 # dtype('float64')
A.size                                  # 15
A.ndim                                  # 2
A.shape                                 # (3, 5)

# Operation
A = np.array([[1.1, 1.2, 2.3],
              [3.4, 5.5, 8.6]])
B = np.array([[3.1, 4.1, 5.9],
              [2.6, 5.3, 5.8]])
A + 2                                   # array([[ 3.1 , 3.2,   4.3 ], [ 5.4,   7.5,  10.6 ]])
A - 2                                   # array([[-0.9 ,-0.8,   0.3 ], [ 1.4,   3.5,   6.6 ]])
A * 2                                   # array([[ 2.2 , 2.4,   4.6 ], [ 6.8,  11.0,  17.2 ]])
A / 2                                   # array([[ 0.55, 0.6,   1.15], [ 1.7,   2.75,  4.3 ]])
A % 2                                   # array([[ 1.1,  1.2,   0.3 ], [ 1.4,   1.5,   0.6 ]])
A **2                                   # array([[ 1.21, 1.44,  5.29], [11.56, 30.25, 73.96]])
A + B                                   # array([[ 4.2,  5.3,   8.2 ], [ 6.0,  10.8,  14.4 ]])
A - B                                   # array([[-2.0, -2.9,  -3.6 ], [ 0.8,   0.2,   2.8 ]])
A * B                                   # Broadcast: array([[ 3.41, 4.92, 13.57], [ 8.84, 29.15, 49.88]])
np.sum(A)                               # 22.1
np.sqrt(A)

# Linear algebra
A = np.matrix(A)
B = np.matrix(B)
np.add(A, B)                            # matrix([[ 4.2,  5.3,  8.2], [ 6. , 10.8, 14.4]])
np.dot(A, B.T)                          # matrix([[21.9 ,22.56], [83.83, 87.87]])
np.trace(A)                             # 6.6
np.linalg.det(np.dot(A, B.T))           # 33.14820000000008
np.linalg.eig(np.dot(A, B.T))

C = np.matrix(A, dtype=np.complex)
type(C)                                 # numpy.matrix
np.conj(C)                              # Conjugate Transpose
C.T                                     # Conjugate Transpose
C.H                                     # Complex Conjugate Transpose
C.I                                     # The inverse matrix

# Special matrices
n = 4
np.identity(n)
    # array([[1., 0., 0., 0.],
    #        [0., 1., 0., 0.],
    #        [0., 0., 1., 0.],
    #        [0., 0., 0., 1.]])
np.eye(n, k =-1)
    # array([[0., 0., 0., 0.],
    #        [1., 0., 0., 0.],
    #        [0., 1., 0., 0.],
    #        [0., 0., 1., 0.]])
np.eye(n, k = 0)
    # array([[1., 0., 0., 0.],
    #        [0., 1., 0., 0.],
    #        [0., 0., 1., 0.],
    #        [0., 0., 0., 1.]])
np.eye(n, k = 1)
    # array([[0., 1., 0., 0.],
    #        [0., 0., 1., 0.],
    #        [0., 0., 0., 1.],
    #        [0., 0., 0., 0.]])
np.eye(n, k = 2)
    # array([[0., 0., 1., 0.],
    #        [0., 0., 0., 1.],
    #        [0., 0., 0., 0.],
    #        [0., 0., 0., 0.]])
np.diag(np.arange(0,6,2))
    # array([[0, 0, 0],
    #        [0, 2, 0],
    #        [0, 0, 4]])
np.diag(np.linspace(0,4,3))
    # array([[0., 0., 0.],
    #        [0., 2., 0.],
    #        [0., 0., 4.]])
np.tri(4, 4,-1)
    # array([[0., 0., 0., 0.],
    #        [1., 0., 0., 0.],
    #        [1., 1., 0., 0.],
    #        [1., 1., 1., 0.]])
np.tri(4, 4, 0)
    # array([[1., 0., 0., 0.],
    #        [1., 1., 0., 0.],
    #        [1., 1., 1., 0.],
    #        [1., 1., 1., 1.]])
np.tri(4, 4, 1)
    # array([[1., 1., 0., 0.],
    #        [1., 1., 1., 0.],
    #        [1., 1., 1., 1.],
    #        [1., 1., 1., 1.]])
np.triu([1,2,3,4],0)
    # array([[1, 2, 3, 4],
    #        [0, 2, 3, 4],
    #        [0, 0, 3, 4],
    #        [0, 0, 0, 4]])

# Operation
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])
np.einsum("n,n", x, y)                  # 70

A = np.arange(0,6).reshape(2,3)         # array([[0, 1, 2],[3, 4, 5]])
B = np.arange(0,6).reshape(3,2)         # array([[0, 1],[2, 3],[4, 5]])
np.dot(A,B)
    # array([[10, 13],
    #        [28, 40]])
np.dot(B,A)
    # array([[ 3,  4,  5],
    #        [ 9, 14, 19],
    #        [15, 24, 33]])
B.dot(A)
    # array([[ 3,  4,  5],
    #        [ 9, 14, 19],
    #        [15, 24, 33]])

C = np.array([[1,2],[3,4]])
D = np.array([[9,8],[7,6]])
C * D                                   # array([[ 9, 16],[21, 24]])
np.dot(C,D)                             # array([[23, 20],[55, 48]])
np.matrix(C)                            # matrix([[1, 2],[3, 4]])
np.matrix(D)                            # matrix([[9, 8],[7, 6]])
np.matrix(C) * np.matrix(D)             # matrix([[23, 20],[55, 48]])

G = np.arange(0,4).reshape(1,4)         # array([[0, 1, 2, 3]])
H = np.arange(0,4).reshape(4,1)         # array([[0],[1],[2],[3]])
np.asmatrix(G)                          # matrix([[0, 1, 2, 3]])
np.asmatrix(H)                          # matrix([[0],[1],[2],[3]])
np.asmatrix(H).T                        # matrix([[0, 1, 2, 3]])
np.asmatrix(H).I
np.asmatrix(H).I * np.asmatrix(H)       # matrix([[1.]])
np.dot(G,H)                             # array([[14]])
np.dot(G,G.T)                           # array([[14]])
np.inner(G,G)                           # array([[14]])
np.inner(H,H)                           # array([[0,0,0,0],[0,1,2,3],[0,2,4,6],[0,3,6,9]])
np.outer(G,G)                           # array([[0,0,0,0],[0,1,2,3],[0,2,4,6],[0,3,6,9]])
np.outer(H,H)                           # array([[0,0,0,0],[0,1,2,3],[0,2,4,6],[0,3,6,9]])

# Kronecker product
P = np.arange(0,9).reshape(3,3)
Q = np.arange(1,5).reshape(2,2)
np.kron(P,Q)
np.kron(Q,P)

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16],
       [ 0,  3,  6,  0,  4,  8],
       [ 9, 12, 15, 12, 16, 20],
       [18, 21, 24, 24, 28, 32]])

In [238]:
## 3D Array functions
T = np.array([[[0.000,0.001,0.002,0.003],[0.010,0.011,0.012,0.013],[0.020,0.021,0.022,0.023],[0.030,0.031,0.032,0.033]],
              [[0.100,0.101,0.102,0.103],[0.110,0.111,0.112,0.113],[0.120,0.121,0.122,0.123],[0.130,0.131,0.132,0.133]],
              [[0.200,0.201,0.202,0.203],[0.210,0.211,0.212,0.213],[0.220,0.221,0.222,0.223],[0.230,0.231,0.232,0.233]],
              [[0.300,0.301,0.302,0.303],[0.310,0.311,0.312,0.313],[0.320,0.321,0.322,0.323],[0.330,0.331,0.332,0.333]]])
T[0,0,0]                                # 0.000
T[1,0,0]                                # 0.100
T[0,1,0]                                # 0.010
T[0,0,1]                                # 0.001

0.001

### Vector
* We suppose:  
    $C  = αE + βA + γB$  
    $c_1 = α + β$  
    $c_2 = βa + γ$  
    $c_3 = γa$  
* We get:  
    $γ  = c3/a$  
    $c_2 = βa + γ = βa + c3/a$  
    $β  = c2/a - c3/a^2$  
    $c_1 = α + β = α + c2/a - c3/a^2$  
    $α  = c1 - c2/a + c3/a^2$  


In [313]:
# Determine the basis
r = 0.05; a = -(1 + r)
E = np.array([1, 0, 0])
A = np.array([1, a, 0])
B = np.array([0, 1, a])
C = np.array([1, 2,-3])

# Coefficients of expansion
α = C[0] - C[1]/a + C[2]/a**2
β = C[1]/a - C[2]/a**2
γ = C[2]/a

α*E + β*A + γ*B                         # array([ 1.,  2., -3.])

# Unit Vectors
def unit_vector(i,n):
    return np.hstack((np.zeros(i-0), 1, np.zeros(n-i-1)))

unit_vector(1,4)                        # array([0., 1., 0., 0.])

array([0., 1., 0., 0.])

## Comprehensions, Dict, and Set

In [333]:
## Set

# Generation
listA = [1, 2, 3, 4, 5, 1, 3, 5]
set(listA)                                  # {1, 2, 3, 4, 5}
A = set(listA); type(set(listA))            # set
len(A)                                      # 5
A.add(6); A                                 # {1, 2, 3, 4, 5, 6}
A.remove(6); A                              # {1, 2, 3, 4, 5}

# logic gates
A = set([1,2,3,4])
B = set([1,3,5,7])
A & B                                       # {1, 3}
A - B                                       # {2, 4}
A | B                                       # {1, 2, 3, 4, 5, 7}
A ^ B                                       # {2, 4, 5, 7}

## Dict
D = {1:1.1, 2:2.2, 3:3.3, 4:4.4}; D         # {1: 1.1, 2: 2.2, 3: 3.3, 4: 4.4}
type(D)                                     # dict
len(D)                                      # 4
D[5] = 5.5; D                               # {1: 1.1, 2: 2.2, 3: 3.3, 4: 4.4, 5: 5.5}

D = {i:i**2 for i in np.arange(1,5,1)}; D   # {1: 1, 2: 4, 3: 9, 4: 16}

## Comprehensions
[i for i in range(10)]                      # [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[i for i in np.arange(0,10,1)]              # [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

# Set
{i for i in [1,1,2,3,4,4,4,3,4,1,2,3]}      # {1, 2, 3, 4}

# Dict
{i: i % 2 == 0 for i in np.arange(0,4)}     # {0: True, 1: False, 2: True, 3: False}

{0: True, 1: False, 2: True, 3: False}

## Class
```Python
class <class name>:
    def __init__(self, params, ...):
        ...
    def method1(self,  params, ...):
        ...
    def method2(self,  params, ...):
        ...    
```

In [317]:
class Name:
    def __init__(self, name):
        self.name = name
        print("Initialized!")
    def Hello(self):
        print("Hello %s!" % self.name)
    def Goodbye(self):
        print("Goodbye %s!" % self.name)

r = Name("David")       # Initialized!
r.Hello()               # Hello David!
r.Goodbye()             # Goodbye David!

Initialized!
Hello David!
Goodbye David!
